version: '3.5'

services:
  milvus-etcd:
    image: quay.io/coreos/etcd:v3.5.18
    container_name: milvus-etcd
    restart: unless-stopped
    environment:
      ETCD_AUTO_COMPACTION_MODE: revision
      ETCD_AUTO_COMPACTION_RETENTION: 1000
      ETCD_QUOTA_BACKEND_BYTES: 4294967296
      ETCD_SNAPSHOT_COUNT: 50000
    command: etcd -advertise-client-urls=http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    volumes:
      - milvus-etcd-data:/etcd

  milvus-minio:
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    container_name: milvus-minio
    restart: unless-stopped
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: minio server /minio_data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - milvus-minio-data:/minio_data

  milvus-standalone:
    image: milvusdb/milvus:v2.5.8
    container_name: milvus-standalone
    restart: unless-stopped
    depends_on:
      - milvus-etcd
      - milvus-minio
    environment:
      ETCD_ENDPOINTS: milvus-etcd:2379
      MINIO_ADDRESS: milvus-minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: ["milvus", "run", "standalone"]
    ports:
      - "19530:19530"
      - "9091:9091"
    volumes:
      - milvus-data:/var/lib/milvus

  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh:ro  # <- importante montare come read-only opzionale
    entrypoint: ["sh", "/entrypoint.sh"]

  app:
    build: .
    container_name: streamlit-app
    restart: unless-stopped
    depends_on:
      - milvus-standalone
      - ollama
    ports:
      - "8501:8501"
    environment:
      MILVUS_HOST: milvus-standalone
      MILVUS_PORT: 19530
      OLLAMA_HOST: ollama
    volumes:
      - .:/app
    working_dir: /app

volumes:
  milvus-etcd-data:
  milvus-minio-data:
  milvus-data:
  ollama-data:
